
name: 'sandbox_external_tables'
version: '1.0'

profile: 'sandbox_external_tables'

config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  +quote_columns: false

models:
  sandbox_external_tables:
    plugins:
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"

sources:
  sandbox_external_tables:
    plugins:
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"

tests:
  sandbox_external_tables:
    plugins:
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"
